name: NPM publish manual
on:
  create:
    tags: 
    - v**

  workflow_dispatch:
    inputs:
      release: 
        description: 'Is release candidate or beta?'
        default: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run build
    - name: get package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: npm publish
      run: npm publish dist/style --tag next
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: npm dist-tags
      if: (!endsWith(github.ref, '-next'))
      run: npm dist-tags add @nicoleoliveira/voce-que-lute-style@${{ steps.package-version.outputs.current-version}}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
